### model
model_name_or_path: meta-llama/Llama-3.1-8B
  
stage: sft
do_train: true
finetuning_type: full
save_total_limit: 1
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: semcoder_sharegpt_office_pyx_inxout_monologue_30k,semcoder_sharegpt_office_pyx_nl2code,rq1_tracefmt_next_sim0.75
template: llama3
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves_ijcai/rq1/llm318base_rq1_tracefmt_next_sim0.75_4a100_full/full/sft
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 5
bf16: true
ddp_timeout: 180000000

report_to: tensorboard

