### model
model_name_or_path: meta-llama/Llama-3.2-3B
  
stage: sft
do_train: true
finetuning_type: full
save_total_limit: 1

deepspeed: examples/deepspeed/ds_z3_config.json
  #deepspeed: examples/deepspeed/ds_z3_offload_config.json

### dataset
dataset: semcoder_sharegpt_office_pyx_inxout_monologue_30k,semcoder_sharegpt_office_pyx_nl2code
template: llama3
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output

output_dir: saves_ijcai/rq1/llama32base_redo_rq1_notrace_baseline_8v100_full/full/sft
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_steps: 5
fp16: true
ddp_timeout: 180000000

report_to: tensorboard

