### model
model_name_or_path: google/gemma-2-9b
  
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_target: all
save_total_limit: 1
#deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
template: gemma
dataset: semcoder_sharegpt_office_pyx_inxout_monologue_30k,semcoder_sharegpt_office_pyx_nl2code,rq1_tracefmt_exe_sim0.75

cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves_ijcai/rq1/gemma2_rq1_tracefmt_exe_sim0.75_4a100_lora64/lora/sft
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 5
bf16: true
ddp_timeout: 180000000

flash_attn: fa2
report_to: tensorboard

